PasswordAuthentication yes
PermitEmptyPasswords no
# Direkt ins Spiel nach Login
ForceCommand socat - TCP:localhost:3490
# Kein echtes Terminal nötig
PermitTTY no
# Sicherheit
PermitRootLogin no
AuthorizedKeysFile none

