[supervisord]
nodaemon=true
loglevel=info

[program:xvfb]
command=Xvfb :99 -screen 0 1280x720x24
autorestart=true
priority=1

[program:newtonwars]
command=/app/run_newtonwars.sh
environment=DISPLAY=":99",LIBGL_ALWAYS_SOFTWARE="1"
autorestart=true
priority=2
startsecs=2

[program:x11vnc]
command=x11vnc -display :99 -nopw -listen 0.0.0.0 -xkb -forever -shared
autorestart=true
priority=3
startsecs=2

[program:novnc]
command=websockify --web /usr/share/novnc 8080 localhost:5900
autorestart=true
priority=4
startsecs=3

[program:sshd]
command=/usr/sbin/sshd -D -e -f /etc/ssh/sshd_config.d/newtonwars.conf
autorestart=true
priority=5
